using SolutionsByText.NET.Models;
using SolutionsByText.NET.Models.Requests;
using SolutionsByText.NET.Models.Requests.Enums;
using SolutionsByText.NET.Models.Requests.Keywords;
using SolutionsByText.NET.Models.Requests.Messages;
using SolutionsByText.NET.Models.Requests.PhoneNumbers;
using SolutionsByText.NET.Models.Requests.Reports;
using SolutionsByText.NET.Models.Requests.SmartUrl;
using SolutionsByText.NET.Models.Requests.Subscriptions;
using SolutionsByText.NET.Models.Requests.Templates;
using SolutionsByText.NET.Models.Requests.Webhooks;
using SolutionsByText.NET.Models.Responses;
using SolutionsByText.NET.Models.Responses.Enums;
using SolutionsByText.NET.Models.Responses.Keywords;
using SolutionsByText.NET.Models.Responses.Messages;
using SolutionsByText.NET.Models.Responses.PhoneNumbers;
using SolutionsByText.NET.Models.Responses.Reports;
using SolutionsByText.NET.Models.Responses.SmartUrl;
using SolutionsByText.NET.Models.Responses.Subscriptions;
using SolutionsByText.NET.Models.Responses.Templates;
using System.Text.Json.Serialization;

namespace SolutionsByText.NET;


[JsonSerializable(typeof(SendMessageRequest))]
[JsonSerializable(typeof(SendTemplateMessageRequest))]
[JsonSerializable(typeof(ScheduleMessageRequest))]
[JsonSerializable(typeof(GetGroupSubscriberStatusRequest))]
[JsonSerializable(typeof(AddGroupSubscriberRequest))]
[JsonSerializable(typeof(ConfirmGroupSubscriberRequest))]
[JsonSerializable(typeof(Relation))]
[JsonSerializable(typeof(DeleteSubscriberRequest))]
[JsonSerializable(typeof(GetOutboundMessagesRequest))]
[JsonSerializable(typeof(GetInboundMessagesRequest))]
[JsonSerializable(typeof(CreateSmartURLRequest))]
[JsonSerializable(typeof(GetPhoneNumberDataRequest))]
[JsonSerializable(typeof(AddBrandSubscriberRequest))]
[JsonSerializable(typeof(ConfirmBrandSubscriberRequest))]
[JsonSerializable(typeof(OutboundMessageStatusRequest))]
[JsonSerializable(typeof(InboundMessageRequest))]
[JsonSerializable(typeof(InboundMMSRequest))]
[JsonSerializable(typeof(SmartUrlClickRequest))]
[JsonSerializable(typeof(DeleteMMSRequest))]
[JsonSerializable(typeof(GetBrandSubscriberStatusRequest))]
[JsonSerializable(typeof(GetDeactivationEventsRequest))]
[JsonSerializable(typeof(GetKeywordsRequest))]
[JsonSerializable(typeof(GetTemplateRequest))]
[JsonSerializable(typeof(GetTemplatesRequest))]
[JsonSerializable(typeof(InboundMessageData))]
[JsonSerializable(typeof(MediaFile))]
[JsonSerializable(typeof(OutboundMessageStatusData))]
[JsonSerializable(typeof(RetrieveMMSRequest))]
[JsonSerializable(typeof(ScheduleTemplateMessageRequest))]
[JsonSerializable(typeof(SmartUrlClickData))]
[JsonSerializable(typeof(Models.Requests.Subscriber))]
[JsonSerializable(typeof(UpdateSmartURLRequest))]
[JsonSerializable(typeof(Variable))]
[JsonSerializable(typeof(WebhookPayload))]
[JsonSerializable(typeof(Property))]
[JsonSerializable(typeof(Address))]
[JsonSerializable(typeof(GetNumberDeactivateEventsRequest))]
[JsonSerializable(typeof(GetAllSmartUrlRequest))]
[JsonSerializable(typeof(GetSmartUrlReportRequest))]
[JsonSerializable(typeof(SmartUrlItem))]
[JsonSerializable(typeof(GetBrandVbtOutboundMessageRequest))]
[JsonSerializable(typeof(GetAllSubscribersGroupRequest))]
[JsonSerializable(typeof(SubscriberExternalApiResponseNew))]
[JsonSerializable(typeof(Models.Responses.Reports.Subscriber), TypeInfoPropertyName = "SubscriberReport")]
[JsonSerializable(typeof(SubscriberData))]
[JsonSerializable(typeof(AddressForGetAllSubcriberInGroup))]
[JsonSerializable(typeof(RelationForGetAllSubcriberInGroup))]
[JsonSerializable(typeof(PropertiesForGetAllSubcriberInGroup))]
[JsonSerializable(typeof(MessageType))]
[JsonSerializable(typeof(OutboundMessageType))]
[JsonSerializable(typeof(InboundMessageType))]
[JsonSerializable(typeof(BrandVBTInboundMessages))]
[JsonSerializable(typeof(VerificationType))]
[JsonSerializable(typeof(DeactivationEventType))]
[JsonSerializable(typeof(MessageReportType))]

[JsonSerializable(typeof(SendMessageResponse))]
[JsonSerializable(typeof(SendTemplateMessageResponse))]
[JsonSerializable(typeof(ScheduleMessageResponse))]
[JsonSerializable(typeof(GetGroupSubscriberStatusResponse))]
[JsonSerializable(typeof(AddSubscriberResponse))]
[JsonSerializable(typeof(AddSubscriber))]
[JsonSerializable(typeof(ConfirmGroupSubscriberResponse))]
[JsonSerializable(typeof(DeleteSubscriberResponse))]
[JsonSerializable(typeof(ReactivateSubscriberRequest))]
[JsonSerializable(typeof(VerificationSettings))]
[JsonSerializable(typeof(ReactivateSubscriberData))]
[JsonSerializable(typeof(ReactivateSubscriberResponse))]
[JsonSerializable(typeof(CancelSubscriptionRequest))]
[JsonSerializable(typeof(CancelSubscriptionResponse))]
[JsonSerializable(typeof(UpdateSubscriberDataRequest))]
[JsonSerializable(typeof(UpdateSubscriberAddress))]
[JsonSerializable(typeof(UpdateSubscriberRelation))]
[JsonSerializable(typeof(UpdateSubscriberProperty))]
[JsonSerializable(typeof(UpdateSubscriberDataResponse))]
[JsonSerializable(typeof(SendODMMessageRequest))]
[JsonSerializable(typeof(SendODMMessageResponse))]
[JsonSerializable(typeof(VerifyODMRequest))]
[JsonSerializable(typeof(VerifyODMData))]
[JsonSerializable(typeof(VerifyODMResponse))]
[JsonSerializable(typeof(GetUsageBrandBreakdownRequest))]
[JsonSerializable(typeof(BrandUsageReportData))]
[JsonSerializable(typeof(ProductTypeUsage))]
[JsonSerializable(typeof(GetUsageBrandBreakdownResponse))]
[JsonSerializable(typeof(GetInboundMessagesResponse))]
[JsonSerializable(typeof(CreateSmartURLResponse))]
[JsonSerializable(typeof(GetPhoneNumberDataResponse))]
[JsonSerializable(typeof(ConfirmBrandSubscriberResponse))]
[JsonSerializable(typeof(ConsentItem))]
[JsonSerializable(typeof(CarrierInfo))]
[JsonSerializable(typeof(CustomParam))]
[JsonSerializable(typeof(DeleteMMSResponse))]
[JsonSerializable(typeof(EventData))]
[JsonSerializable(typeof(DeactEventReportAccount))]
[JsonSerializable(typeof(SubscriberResponseInbox))]
[JsonSerializable(typeof(UserDetails))]
[JsonSerializable(typeof(SubscriberCustomParams))]
[JsonSerializable(typeof(BrandVbtMessageReportResponse))]
[JsonSerializable(typeof(BrandVbtMessageReportResponsePaginatedResponse2))]
[JsonSerializable(typeof(GetDeactivationEventsResponse))]
[JsonSerializable(typeof(GetKeywordsResponse))]
[JsonSerializable(typeof(GetOutboundMessagesResponse))]
[JsonSerializable(typeof(GetTemplateResponse))]
[JsonSerializable(typeof(GetTemplatesResponse))]
[JsonSerializable(typeof(WebhookMessage))]
[JsonSerializable(typeof(KeywordItem))]
[JsonSerializable(typeof(KeywordPaginatedData))]
[JsonSerializable(typeof(PaginationData))]
[JsonSerializable(typeof(PhoneNumberData))]
[JsonSerializable(typeof(RetrieveMMSResponse))]
[JsonSerializable(typeof(ScheduleTemplateMessageResponse))]
[JsonSerializable(typeof(SubscriberStatus))]
[JsonSerializable(typeof(TemplateItem))]
[JsonSerializable(typeof(UpdateSmartURLResponse))]
[JsonSerializable(typeof(User))]
[JsonSerializable(typeof(InboundOutboundMessagesData))]
[JsonSerializable(typeof(MediaDetails))]
[JsonSerializable(typeof(MediaPath))]
[JsonSerializable(typeof(GetBrandSubscriberStatusResponse))]
[JsonSerializable(typeof(GetNumberDeactivateEventsResponse))]
[JsonSerializable(typeof(PaginatedNumberDeactivateEvents))]
[JsonSerializable(typeof(CarrierChange))]
[JsonSerializable(typeof(GetAllSmartUrlResponse))]
[JsonSerializable(typeof(GetSmartUrlClickReportResponse))]
[JsonSerializable(typeof(SmartUrlClickReport))]
[JsonSerializable(typeof(SmartUrlBaseItem))]
[JsonSerializable(typeof(GetSmartUrlDetailClickReportResponse))]
[JsonSerializable(typeof(SmartUrlDetailClickReport))]
[JsonSerializable(typeof(GetBrandVbtMessageResponse))]
[JsonSerializable(typeof(BrandVbtMessage))]
[JsonSerializable(typeof(TokenResponse))]
[JsonSerializable(typeof(MessageData))]
[JsonSerializable(typeof(GetAllSubscribersGroupResponse))]
[JsonSerializable(typeof(AllSubscriberGroup))]
[JsonSerializable(typeof(ConfirmBrandSubscriber))]
[JsonSerializable(typeof(PaginatedSmartUrlResponse))]
[JsonSerializable(typeof(PaginatedEventData))]
[JsonSerializable(typeof(PaginatedSmartUrlClickReport))]
[JsonSerializable(typeof(PaginatedSmartUrlDetailClickReport))]
[JsonSerializable(typeof(PaginatedBrandVbtMessage))]
[JsonSerializable(typeof(PaginatedAllSubscribersGroup))]
[JsonSerializable(typeof(ConfirmGroupSubscriber))]
[JsonSerializable(typeof(TemplateMessage))]
[JsonSerializable(typeof(MessageStatus))]
[JsonSerializable(typeof(ScheduleStatus))]
[JsonSerializable(typeof(OperationStatus))]
[JsonSerializable(typeof(CarrierType))]
[JsonSerializable(typeof(ErrorCode))]
[JsonSerializable(typeof(StatusCode))]

[JsonSerializable(typeof(ApiResponse<AddSubscriberResponse>))]
[JsonSerializable(typeof(ApiResponse<AddSubscriber>))]
[JsonSerializable(typeof(ApiResponse<List<ConsentItem>>))]
[JsonSerializable(typeof(ApiResponse<GetBrandSubscriberStatusResponse>))]
[JsonSerializable(typeof(ApiResponse<string>))]
[JsonSerializable(typeof(ApiResponse<PaginatedNumberDeactivateEvents>))]
[JsonSerializable(typeof(ApiResponse<PaginatedSmartUrlResponse>))]
[JsonSerializable(typeof(ApiResponse<PaginatedEventData>))]
[JsonSerializable(typeof(ApiResponse<KeywordPaginatedData>))]
[JsonSerializable(typeof(ApiResponse<InboundOutboundMessagesData>))]
[JsonSerializable(typeof(ApiResponse<TemplateItem>))]
[JsonSerializable(typeof(ApiResponse<PaginatedSmartUrlClickReport>))]
[JsonSerializable(typeof(ApiResponse<List<SubscriberStatus>>))]
[JsonSerializable(typeof(List<SubscriberStatus>))]
[JsonSerializable(typeof(ApiResponse<PaginatedSmartUrlDetailClickReport>))]
[JsonSerializable(typeof(ApiResponse<SendMessageResponse>))]
[JsonSerializable(typeof(ApiResponse<MessageData>))]
[JsonSerializable(typeof(ApiResponse<PhoneNumberData>))]
[JsonSerializable(typeof(ApiResponse<GetPhoneNumberDataResponse>))]
[JsonSerializable(typeof(ApiResponse<GetGroupSubscriberStatusResponse>))]
[JsonSerializable(typeof(ApiResponse<BrandVbtMessageReportResponsePaginatedResponse2>))]
[JsonSerializable(typeof(ApiResponse<PaginatedAllSubscribersGroup>))]
[JsonSerializable(typeof(ApiResponse<GetAllSubscribersGroupResponse>))]
[JsonSerializable(typeof(ApiResponse<ConfirmGroupSubscriber>))]
[JsonSerializable(typeof(ApiResponse<ConfirmGroupSubscriberResponse>))]
[JsonSerializable(typeof(ApiResponse<ConfirmBrandSubscriberResponse>))]
[JsonSerializable(typeof(ApiResponse<ConfirmBrandSubscriber>))]
[JsonSerializable(typeof(ApiResponse<string>))]
[JsonSerializable(typeof(ApiResponse<GetDeactivationEventsResponse>))]
[JsonSerializable(typeof(ApiResponse<GetNumberDeactivateEventsResponse>))]
[JsonSerializable(typeof(ApiResponse<GetAllSmartUrlResponse>))]
[JsonSerializable(typeof(ApiResponse<GetSmartUrlClickReportResponse>))]
[JsonSerializable(typeof(ApiResponse<GetSmartUrlDetailClickReportResponse>))]
[JsonSerializable(typeof(ApiResponse<GetOutboundMessagesResponse>))]
[JsonSerializable(typeof(ApiResponse<GetBrandVbtMessageResponse>))]
[JsonSerializable(typeof(ApiResponse<GetTemplatesResponse>))]
[JsonSerializable(typeof(ApiResponse<List<TemplateItem>>))]
[JsonSerializable(typeof(ApiResponse<GetInboundMessagesResponse>))]
[JsonSerializable(typeof(ApiResponse<SendTemplateMessageResponse>))]
[JsonSerializable(typeof(ApiResponse<TemplateMessage>))]
[JsonSerializable(typeof(ApiResponse<DeleteMMSResponse>))]
[JsonSerializable(typeof(ApiResponse<DeleteSubscriberResponse>))]
[JsonSerializable(typeof(ErrorResponse))]

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    WriteIndented = true,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
public partial class SolutionsByTextJsonContext : JsonSerializerContext
{
}

